### ISSUE TITLE
Make the library compatible with Capacitor 6.0

### ISSUE THREAD

**Issue by TomDoesb** [Craig-Ronald/capacitor-subscriptions#12]
We want to upgrade to capacitor 6 however this plugin is not (yet) compatible.

https://capacitorjs.com/docs/updating/plugins/6-0

**Comment by CraigRonald555** [comment]
> We want to upgrade to capacitor 6 however this plugin is not (yet) compatible.
> 
> 
> 
> https://capacitorjs.com/docs/updating/plugins/6-0

Thanks for letting me know - updating seems fairly simple. Should have the fixes done by the end of the weekend.

**Comment by TomDoesb** [comment]
Did you manage to make the change?

**Comment by CraigRonald555** [comment]
> Did you manage to make the change? 

I've updated the package but it's still on its own branch awaiting to be merged. 

I was having issues with XCode over the weekend so wasn't able to properly test it. 

I'm hoping to find some time in the evening this week to properly test and deploy it.

**Comment by TomDoesb** [comment]
Sorry to bother you again :P but any updates? Otherwise I will plan some time to downgrade to 5.0 again

**Comment by CraigRonald555** [comment]
> Sorry to bother you again :P but any updates? Otherwise I will plan some time to downgrade to 5.0 again

Sorry I got a bit side-tracked, thanks for reminding me! 

I'll complete the testing today and as long as long as there's no massive issues, I'll have it released by the end of the day.

**Comment by CraigRonald555** [comment]
> Sorry to bother you again :P but any updates? Otherwise I will plan some time to downgrade to 5.0 again

Hello again, just released an alpha version with Capacitor 6 upgrades. I ran some manual tests on iOS and will do the same with Android when I get home later. All should be well but if you run into any issues during development please let me know and I'll sort it!

**Comment by TomDoesb** [comment]
Hi, In my first tests iOS seems to work fine. (we're not using Android). I've handed it over to our tester. I'll let you know if she finds anything.

**Comment by TomDoesb** [comment]
All seems fine on the iOS front, thanks for your efforts!

**Comment by CraigRonald555** [comment]
> All seems fine on the iOS front, thanks for your efforts!

Awesome! Thank you for testing, glad the update went well 👍

**Comment by nesha14586** [comment]
> All seems fine on the iOS front, thanks for your efforts!

@TomDoesb everything worked fine with your app? I see the PR is still open for this.
